### ISSUE TITLE
An error "Cannot GET /" happened when i run drawdb-server using docker locally

### ISSUE THREAD

**Issue by Xuquansheng** [drawdb-io/drawdb-server#1]
Hi, 
   Below is my Dockerfile

root@app:~/drawdb-server# more Dockerfile
FROM node:20

# Create a working directory
WORKDIR /app

# Install dependencies
COPY . .
RUN npm install

ENV CLIENT_URL=http://localhost:5173
ENV EMAIL_PASS=very-secret-email-password
ENV EMAIL_REPORT=email@outlook.com
ENV EMAIL_USER=email@outlook.com
ENV PORT=5000

# Expose the port that the application will run on
EXPOSE 5000

# Start the application
CMD ["node", "index.js"]

**Comment by 1ilit** [comment]
Hey! This is expected behavior.  There is no route "/" that the server supports. The only available route is "/send_email"
